cirrus_hello_task: &hello
  container:
    image: gcc:latest
  env:
    HELLO: hello
  test_script: echo ${HELLO} world. && sleep 300

cirrus_test1_task: *hello

cirrus_test2_task:
  <<: *hello
  env:
    HELLO: Hello
  depends_on:
    - cirrus_test1
