kind: pipeline
name: main

aliases:
  - test_command: &test-cmd echo test command

clone: &clone-default
  depth: 1

steps: &base
  - name: test
    image: gcc
    commands: *test-cmd
  - name: test2
    image: gcc
    commands: *test-cmd
    when: &condition
      branch:
        - master
  - name: test3
    image: gcc
    commands:
      - echo test3
    when:
      <<: *condition
      event:
        - push

# ---
# kind: pipeline
# name: copy

# clone: *clone-default

# steps:
#   - name: hello
#     image: gcc
#     when: *condition
#     commands:
#       - echo hello
