kind: pipeline
name: main

clone: &clone-default
  depth: 1

steps: &base
  - name: test
    image: gcc
    commands: &test-cmd
      - echo test
  - name: test2
    image: gcc
    commands: *test-cmd
  - name: test3
    image: gcc
    commands:
      - echo hello
      <<: *test-cmd
  

# ---
# kind: pipeline
# name: copy

# clone: *clone-default

# steps:
#   <<: *base
#   - name: hello
#     image: gcc
#     commands:
#       - echo hello
