kind: pipeline
name: main

clone: &clone-default
  depth: 1

steps: &base
  - name: test
    image: gcc
    commands:
      - echo test

---
kind: pipeline
name: copy

clone: *clone-default

steps:
  <<: *base
  - name: hello
    image: gcc
    commands:
      - echo hello
