version: v2

aliases:
  - &test
    containers:
      - image: gcc
    variables:
      - HELLO=hello
    steps:
      - commands:
        - echo ${HELLO}

tasks:
  test1: *test
  test2:
    <<: *test
    containers:
      - image: gcc:9.3.0
    variables:
      - HELLO=Hello
