aliases:
  - &test
    image: gcc
    variables:
      - HELLO=hello
    commands:
      - echo ${HELLO}
tasks:
  test1: *test
  test2:
    <<: *test
    image: gcc:9.3.0
    variables:
      - HELLO=Hello
