tasks:
  test: &test
    image: gcc
    variables:
      - HELLO=hello
    commands:
      - echo ${HELLO}
  test2: *test
  test3:
    <<: *test
    image: gcc:9.3.0
    variables:
      - HELLO=Hello
