build:
  nodes:
    test1: &test_base
      environment:
        python: 3.6.0
        variables:
          HELLO: hello
      tests:
        override:
          - echo ${HELLO}
    test2: *test_base
    test3:
      <<: *test_base
      environment:
        variables:
          HELLO: Hello
    analysis:
      tests:
        override:
            - py-scrutinizer-run
        
filter:
  excluded_paths:
    - '*'

checks:
  python:
    code_rating: true
    duplicate_code: true
    classes_valid_slots: true
