build:
  environment:
    python: 3.6.0
    variables:
      HELLO: hello
  tests:
    override:
      - echo ${HELLO}

filter:
  excluded_paths:
    - '*'

checks:
  python:
    code_rating: true
    duplicate_code: true
    classes_valid_slots: true
