build:
    nodes:
        hello: &hello
            environment:
                python: 3.6.0
                variables:
                  HELLO: hello
            tests:
                override:
                    - echo OK
        hello2: *hello
        
filter:
    excluded_paths:
        - '*'

checks:
    python:
        code_rating: true
        duplicate_code: true
        classes_valid_slots: true
