dist: xenial

language: cpp

compiler:
  - clang
  - gcc

addons:
  apt: &apt-global
    sources: &apt-common-sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-6.0
      - llvm-toolchain-xenial
    packages: &apt-common-packages
      - g++-8
      - gcc-8

script:
  - g++-8 --version || true
  - clang-6.0 --version || true
  - echo OK

matrix:
  include:
    - &base
      compiler: gcc
      env: TEST2
    - compiler: clang
      env: TEST1
      addons:
        apt:
          sources: *apt-common-sources
          packages:
            - *apt-common-packages
            - clang-6.0
    - <<: *base
      env: TEST3

notifications:
  email: false
