aliases:
  - execution: &default-execution
      onStart:
        - update_commit_status ci_yaml_gitRepo # Status: "processing"
      onExecute:
        - update_commit_status ci_yaml_gitRepo # Status: "processing"
      onFailure:
        - update_commit_status ci_yaml_gitRepo # Status: "failure"
      onSuccess:
        - update_commit_status ci_yaml_gitRepo # Status: "success"

  - onExecute: &default-execute
    - update_commit_status ci_yaml_gitRepo # Status: "processing"
    - pushd ${res_ci_yaml_gitRepo_resourcePath}
    - echo OK
    - popd

resources:
  - name: ci_yaml_gitRepo
    type: GitRepo
    configuration:
      gitProvider: GitHub
      path: srz-zumix/ci-yaml
      branches:
        include: master|^feature/.*
pipelines:
  - name: ci_yaml_1
    steps: &default-steps
      - name: step
        type: Bash
        configuration:
          inputResources:
            - name: ci_yaml_gitRepo
        execution: *default-execution
          onExecute: *default-execute
  - name: ci_yaml_2
    steps: *default-steps
  # error:YAMLException: cannot merge mappings
  # - name: ci_yaml_3
  #   steps:
  #     - name: step
  #       type: Bash
  #       configuration:
  #         inputResources:
  #           - name: ci_yaml_gitRepo
  #       execution:
  #         <<: *default-execute
  #         # - echo Hoge
  # error:YAMLException: cannot merge mappings
  # - name: ci_yaml_4
  #   steps:
  #     <<: *default-steps
  #     # configuration:
  #     #   inputResources:
  #     #     - name: ci_yaml_gitRepo
  #     #   inputSteps:
  #     #     - name: ci_yaml_1
