aliases:
  - image: &default-image circleci/buildpack-deps:cosmic-browsers
  - &hello
    name: Greeting
    command: echo ${HELLO}, ${WORLD}.
  - &env-hello
    HELLO: hello

version: 2
jobs:
  build1:
    docker:
      - image: *default-image
    environment: &hello_env
      HELLO: hello
    steps:
      - checkout
      - run: *hello
      - run:
          name: Print the Current Time
          command: date
      - run: *hello
  build2:
    docker:
      - image: *default-image
    environment:
      <<: *hello_env
      WORLD: world
    steps:
      - checkout
      - run: *hello

workflows:
  version: 2
  default-test:
    jobs:
      - build1
      - build2
