name: CI

on: [push]

jobs:
  build: # &base
    runs-on: ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo ${HELLO}, world!
      env:
        HELLO: hello
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  # build2: *base
