name: CI

on: [push]

jobs:
  build: # &base
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo ${HELLO}, world!
      env:
        HELLO: hello
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  # build2: *base

  pair-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        A: [""]
        B: [""]
        C: ["!"]
        exclude:
          - A: ""
        include:
          - A: "Hello"
            B: "world"
          - A: "Good"
            B: "bye"
    steps:
      - run: echo "${{ matrix.A }}-${{ matrix.B }} ${{ matrix.C }}"

  array-pair-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pair:
          - ["Hello", "world"]
          - ["Good", "bye"]
    steps:
      - run: echo "${{ matrix.pair[0] }}-${{ matrix.pair[1] }}"
