name: search

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        filename:
          - .cirrus.yml
          - .circleci/config.yml
          - .drone.yml
          - .github/workflows/*.yml
          - .travis.yml
          - appveyor.yml
          - bitrise.yml
          - buddy.yml
          - codefresh.yml
          - shippable.yml
          - sider.yml
          - wercker.yml
    steps:
    - uses: actions/checkout@v1
    - run: |
        curl -s -u :${{ secrets.github_token }} https://api.github.com/search/code?q=filename:"${{ matrix.filename }}"+extension:yml+path:/ | jq ".total_count"
