name: search

on: [push]

jobs:
  search:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        query:
          - filename:"appveyor.yml"+extension:yml+path:/
          - filename:"azure-pipelines.yml"+extension:yml+path:/
          - filename:"bitrise.yml"+extension:yml+path:/
          - filename:"buddy.yml"+extension:yml+path:/
          - filename:"config.yml"+extension:yml+path:/circleci/
          - filename:".cirrus.yml"+extension:yml+path:/
          - filename:".drone.yml"+extension:yml+path:/
          - filename:*.yml+extension:yml+path:/.github/workflows/
          - filename:"codecov.yml"+extension:yml+path:/
          - filename:"codefresh.yml"+extension:yml+path:/
          - filename:"peak_flow.yml"+extension:yml+path:/
          - filename:"rocro.yml"+extension:yml+path:/
          - filename:"semaphore.yml"+extension:yml+path:/.semaphore/
          - filename:"shippable.yml"+extension:yml+path:/
          - filename:"sider.yml"+extension:yml+path:/
          - filename:".travis.yml"+extension:yml+path:/
          - filename:"wercker.yml"+extension:yml+path:/
    steps:
    - name: search
      id: search_yaml
      run: |
        TOTAL_COUNT=$(curl -s -u :${{ secrets.github_token }} https://api.github.com/search/code?q=filename:${{ matrix.filename }}+extension:yml+path:/ | jq ".total_count")
        echo ${TOTAL_COUNT}
        QUERY=${{ matrix.query }}
        JSON="{ ${QUERY//+/,} }"
        echo ${JSON}
        QF=$(echo ${JSON} | jq ".filename")
        QP=$(echo ${JSON} | jq ".path")
        SEARCH="${QP}${QF}"
        FILEPATH_=${SEARCH%%/*}
        FILEPATH=$(basename ${FILEPATH_})
        FILENAME_=${FILEPATH%.yml}
        FILENAME=${FILENAME_#.}
        echo ${FILENAME}, ${TOTAL_COUNT} > ${FILENAME}.txt
        echo "##[set-output name=filename;]$(echo ${FILENAME}.txt)"
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: search
        path: ${{ steps.search_yaml.outputs.filename }}

  collect:
    runs-on: ubuntu-latest
    needs: search
    steps:
    - name: Download
      uses: actions/download-artifact@v1
      with:
        name: search
    - name: collect
      run: |
        ls ./search
        for f in ./search/*; do cat $f >> result.csv; done
    - name: result
      run: |
        cat result.csv
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: result
        path: result.csv

