name: search

on: [push]

jobs:
  search:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        filename:
          - appveyor.yml
          - azure-pipelines.yml
          - bitrise.yml
          - buddy.yml
          - .circleci/config.yml
          - .cirrus.yml
          - .drone.yml
          - .github/workflows/*.yml
          - codecov.yml
          - codefresh.yml
          - peak_flow.yml
          - rocro.yml
          - .semaphore/semaphore.yml
          - shippable.yml
          - sider.yml
          - .travis.yml
          - wercker.yml
    steps:
    - name: search
      id: search_yaml
      run: |
        TOTAL_COUNT=$(curl -s -u :${{ secrets.github_token }} https://api.github.com/search/code?q=filename:"${{ matrix.filename }}"+extension:yml+path:/ | jq ".total_count")
        echo ${TOTAL_COUNT}
        SEARCH=${{ matrix.filename }}
        FILEPATH_=${SEARCH%%/*}
        FILEPATH=$(basename ${FILEPATH_})
        FILENAME_=${FILEPATH%.yml}
        FILENAME=${FILENAME_#.}
        echo ${FILENAME}, ${TOTAL_COUNT} > ${FILENAME}.txt
        echo "##[set-output name=filename;]$(echo ${FILENAME}.txt)"
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: search
        path: ${{ steps.search_yaml.outputs.filename }}

  collect:
    runs-on: ubuntu-latest
    needs: search
    steps:
    - name: Download
      uses: actions/download-artifact@v1
      with:
        name: search
    - name: collect
      run: |
        ls ./search
        for f in ./search/*; do cat $f >> result.csv; done
    - name: result
      run: |
        cat result.csv
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: result
        path: result.csv

