name: search

on: [push]

jobs:
  search:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        filename:
          - appveyor.yml
          - azure-pipelines.yml
          - bitrise.yml
          - buddy.yml
          # - config.yml
          - circle.yml
          - .cirrus.yml
          - codecov.yml
          - codefresh.yml
          - codeship-steps.yml
          - .drone.yml
          # - "*.yml"
          - "*jfrog*.yml"
          - peak_flow.yml
          - .razorops.yaml
          - .scrutinizer.yml
          # - semaphore.yml
          - sider.yml
          - .travis.yml
          - wercker.yml
        path: ["/"]
        include:
          - filename: config.yml
            path: /.circleci/
          - filename: "*.yml"
            path: /.github/workflows/
          - filename: semaphore.yml
            path: /.semaphore/
    steps:
    - name: search
      id: search_yaml
      run: |
        QF=${{ matrix.filename }}
        QP=${{ matrix.path }}
        TOTAL_COUNT=$(curl -s -u :${{ secrets.github_token }} https://api.github.com/search/code?q=filename:${QF}+path:${QP} | jq ".total_count")
        # TOTAL_COUNT=$(curl -s -u :${{ secrets.github_token }} https://api.github.com/search/code?q=filename:${QF}+extension:yml+path:${QP} | jq ".total_count")
        echo ${TOTAL_COUNT}
        QF_=$(echo $QF | sed 's/\*//g')
        SEARCH=${QP#/}${QF_}
        FILEPATH_=${SEARCH%%/*}
        FILEPATH=$(basename ${FILEPATH_})
        FILENAME_1=${FILEPATH%.yml}
        FILENAME_2=${FILENAME_1%.yaml}
        FILENAME=${FILENAME_2#.}
        echo ${FILENAME}, ${TOTAL_COUNT} > ${FILENAME}.txt
        echo "##[set-output name=filename;]$(echo ${FILENAME}.txt)"
        # echo "::warning:: ${FILENAME}, ${TOTAL_COUNT}"
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: search
        path: ${{ steps.search_yaml.outputs.filename }}
    - name: Wait
      run: |
        sleep 60

  collect:
    runs-on: ubuntu-latest
    needs: search
    steps:
    - name: Download
      uses: actions/download-artifact@v1
      with:
        name: search
    - name: collect
      run: |
        ls ./search
        for f in ./search/*; do cat $f >> result.csv; done
    - name: result
      run: |
        RESULT=$(cat result.csv)
        echo "${RESULT}"
    - name: annotation
      run: |
        ANNOTATION=$(cat -e result.csv)
        echo ${ANNOTATION}
        echo "::warning:: ${ANNOTATION//$\n/, }"
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: result
        path: result.csv

