name: search

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        filename:
          - .travis.yml
    steps:
    - uses: actions/checkout@v1
    - run: |
        curl -s -u :${{ secrets.github_token }} https://api.github.com/search/code?q=filename:"${{ matrix.filename }}"+extension:yml+path:/ | jq ".total_count"
